#!/bin/sh

# Автостарт
pkill polybar 
pkill sxhk
sxhkd &
polybar mybar &
picom &
dunst &
emacs --daemon &

feh --randomize --no-fehbg --bg-scale ~/images/

# Рабочие столы
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Запуск polybar
~/.config/polybar/launch.sh &

# Рамки и Гапсы
bspc config border_width         2
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"
bspc config presel_feedback_color "#23252e"


bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	     true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      true
