#!/bin/sh

# Автостарт
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
dunst &
emacs --daemon &
xsetroot -cursor_name left_ptr &

# xsetroot -cursor_name left_ptr
xrdb merge ~/.Xresources

# Запуск polybar
~/bin/launch-polybar.sh &

feh --randomize --no-fehbg --bg-scale ~/images/

# Рабочие столы
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Рамки и отступы
bspc config border_width 2
bspc config window_gap   10
bspc config top_padding  35

# Цвета границ окон
bspc config normal_border_color   "#23252e"
bspc config active_border_color   "#23252e"
bspc config focused_border_color  "#f9f8fe"
bspc config presel_feedback_color "#23252e"

# Использование мыши
bspc config focus_follows_pointer true
bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

# Полноэкранный режим
bspc config single_monocle      true
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config paddingless_monocle true

# Разбиение окон
bspc config split_ratio          0.5
