[[language]]
name = "python"
language-servers = [ "ruff" , "pyright" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "off"
autoImportCompletions = true

[language-server.ruff]
command = "ruff"
args = ["server"]
[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[[language]]
name = "c"
auto-format = false
formatter = { command = "clang-format" }
language-servers = [ "clangd" ]
